In [1]:
import sys, os, fnmatch, datetime, subprocess, imp
import numpy as np
from collections import defaultdict
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
lib = pd.read_csv('061318_exonskipping_library.csv', index_col=0, usecols = ('Identifier number', 'Designed 61-bp target site (37i-24e, AG)', 'gRNA', 'Designed gRNA (NGG orientation)'))

In [3]:
lib = lib.reset_index('Identifier number')
lib =  lib.rename(columns = {'Designed 61-bp target site (37i-24e, AG)':'target_site', 'Identifier number':'id'})

In [4]:
lib.groupby(['id']).count()

       target_site  gRNA  Designed gRNA (NGG orientation)
id
2                1     1                                1
3                1     1                                1
4                1     1                                1
5                1     1                                1
6                1     1                                1
7                1     1                                1
8                1     1                                1
9                1     1                                1
11               1     1                                1
12               1     1                                1
13               1     1                                1
22               1     1                                1
28               1     1                                1
29               1     1                                1
32               1     1                                1
33               1     1                                1
34               1     1                                1
35               1     1                                1
39               1     1                                1
40               1     1                                1
51               1     1                                1
52               1     1                                1
67               1     1                                1
68               1     1                                1
70               1     1                                1
71               1     1                                1
72               1     1                                1
73               1     1                                1
74               1     1                                1
75               1     1                                1
...            ...   ...                              ...
10988            1     1                                1
10989            1     1                                1
10990            1     1                                1
10992            1     1                                1
10999            1     1                                1
11006            1     1                                1
11007            1     1                                1
11009            1     1                                1
11011            1     1                                1
11012            1     1                                1
11015            1     1                                1
11016            1     1                                1
11017            1     1                                1
11018            1     1                                1
11019            1     1                                1
11020            1     1                                1
11021            1     1                                1
11022            1     1                                1
11023            1     1                                1
11024            1     1                                1
11025            1     1                                1
11026            1     1                                1
11027            1     1                                1
11035            1     1                                1
11036            1     1                                1
11039            1     1                                1
11040            1     1                                1
11041            1     1                                1
11042            1     1                                1
11057            1     1                                1

[4000 rows x 3 columns]

In [5]:
target_sites = lib.groupby('target_site').count().reset_index('target_site')
target_unique = target_sites.loc[target_sites.id == 1]

target_dict = pd.Series(target_unique.id.values, index = target_unique.target_site).to_dict()

lib['unique_target'] = lib.target_site.apply(lambda x: True if x in target_dict else False)
lib = lib.loc[lambda x: x.unique_target == True]

In [24]:
lib.to_csv('unique_targets.csv', columns = ('id','target_site'), index = False)